- alias: "Receive Hallway Switch State Update"
  trigger:
    - platform: webhook
      webhook_id: shelly_cor
  condition:
    - condition: template
      value_template: "{{ trigger.json.token == 'xxxxx' }}"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.hallway_switch_updated_by_webhook
    - service: input_text.set_value
      target:
        entity_id: input_text.hallway_switch_state
      data:
        value: "{{ trigger.json.state }}"

- id: button_1_short_click_activate_blinds_vent_scene
  alias: Button 1 Short Click - Activate Blinds Vent Scene
  description: ''
  triggers:
  - entity_id:
    - sensor.switch4bed_switch4bed_action
    to: 1_single
    trigger: state
  - platform: mqtt
    topic: "zigbee2mqtt/switch4bed/action"
    payload: "1_single"
  actions:
  - target:
      entity_id: scene.blinds_vent_bedroom
    action: scene.turn_on
    data: {}

- id: SwsUsbLamp
  alias: SwsUsbLamp
  description: ""
  triggers:
    - trigger: state
      entity_id: sensor.switch4StudyDesk_switch4StudyDesk_action
      to: 2_single
    - trigger: mqtt
      options:
        topic: zigbee2mqtt/switch4StudyDesk/action
        payload: 2_single
  conditions: []
  actions:
    - action: switch.toggle
      metadata: {}
      data: {}
      target:
        entity_id: switch.shelly_power_strip_gen4_switch_3
  mode: single
