input_text:
  hallway_switch_state:
    name: "Hallway switch state"
    initial: "off"

input_boolean:
  hallway_switch_updated_by_webhook:
    name: "Hallway Updated by Webhook"
    initial: off
  blinds_guest_mode:
    name: "Blinds Guest Mode"
    initial: false
  blinds_automation_enabled:
    name: "Blinds Automation enabled"
    initial: true
  blinds_bedroom_automation_enabled:
    name: "Blinds Bedroom enabled"
    initial: false

input_datetime:
  blinds_weekday_open_time:
    name: Blinds Weekday Open Time
    has_date: false
    has_time: true
  blinds_weekday_guest_open_time:
    name: Blinds Guest Weekday Open Time
    has_date: false
    has_time: true

switch:
  - platform: template
    switches:
      hallway_switch:
        friendly_name: "Hallway Switch"
        value_template: "{{ states('input_text.hallway_switch_state') == 'on' }}"
        turn_on:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.hallway_switch_updated_by_webhook
            - service: input_text.set_value
              target:
                entity_id: input_text.hallway_switch_state
              data:
                value: "on"
        turn_off:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.hallway_switch_updated_by_webhook
            - service: input_text.set_value
              target:
                entity_id: input_text.hallway_switch_state
              data:
                value: "off"
