input_text:
  hallway_switch_state:
    name: "Hallway switch state"
    initial: "off"

input_number:
  blinds_living_position:
    name: "Blinds Living room position"
    initial: 35
    step: 1
    mode: box
    min: 0
    max: 100
  blinds_living_tilt:
    name: "Blinds Living room tilt"
    initial: 0.9
    step: 0.1
    mode: box
    min: 0
    max: 3
  blinds_tilt:
    name: "Blinds tilt"
    initial: 0.9
    step: 0.1
    mode: box
    min: 0
    max: 3

input_boolean:
  hallway_switch_updated_by_webhook:
    name: "Hallway Updated by Webhook"
    initial: off
  blinds_guest_mode:
    name: "Blinds Guest Mode"
    initial: false
  blinds_automation_enabled:
    name: "Blinds Automation enabled"
    initial: true
  blinds_bedroom_automation_enabled:
    name: "Blinds Bedroom enabled"
    initial: false
  blinds_dusk_automation_enabled:
    name: "Blinds Dusk Automation enabled"
    initial: true
  blinds_full_open_automation_enabled:
    name: "Blinds Full Open Automation enabled"
    initial: true
  blinds_night_venting_enabled:
    name: "Blinds Night Venting enabled"
    initial: true
  blinds_close_on_dawn_enabled:
    name: "Blinds Close on Dawn enabled"
    initial: true
  blinds_winter_mode_enabled:
    name: "Blinds Winter Mode enabled"
    initial: false
  blinds_morning_automation_enabled:
    name: "Morning automation enabled"
    initial: false
  blinds_morning_weekend_automation_enabled:
    name: "Morning weekend automation enabled"
    initial: false

input_datetime:
  blinds_weekday_open_time:
    name: Blinds Weekday Open Time
    has_date: false
    has_time: true
  blinds_weekday_guest_open_time:
    name: Blinds Guest Weekday Open Time
    has_date: false
    has_time: true
  blinds_weekends_open_time:
    name: Blinds Weekends Open Time
    has_date: false
    has_time: true
  blinds_weekends_guest_open_time:
    name: Blinds Guest Weekends Open Time
    has_date: false
    has_time: true
  blinds_dusk_offset:
    name: Blinds Dusk offset
    has_date: false
    has_time: true
    initial: "12:00"
  blinds_pre_dusk_offset:
    name: Blinds Pre Dusk offset
    has_date: false
    has_time: true
    initial: "12:00"
  blinds_pre_dusk_final:
    name: Blinds Pre Dusk final
    has_date: true
    has_time: true
  blinds_dusk_final:
    name: Blinds Dusk final
    has_date: true
    has_time: true

switch:
  - platform: template
    switches:
      hallway_switch:
        friendly_name: "Hallway Switch"
        value_template: "{{ states('input_text.hallway_switch_state') == 'on' }}"
        turn_on:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.hallway_switch_updated_by_webhook
            - service: input_text.set_value
              target:
                entity_id: input_text.hallway_switch_state
              data:
                value: "on"
        turn_off:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.hallway_switch_updated_by_webhook
            - service: input_text.set_value
              target:
                entity_id: input_text.hallway_switch_state
              data:
                value: "off"
