input_text:
  hallway_switch_state:
    name: "Hallway switch state"
    initial: "off"

input_boolean:
  hallway_switch_updated_by_webhook:
    name: "Updated by Webhook"
    initial: off

switch:
  - platform: template
    switches:
      hallway_switch:
        friendly_name: "Hallway Switch"
        value_template: "{{ states('input_text.hallway_switch_state') == 'on' }}"
        turn_on:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.hallway_switch_updated_by_webhook
            - service: input_text.set_value
              target:
                entity_id: input_text.hallway_switch_state
              data:
                value: "on"
        turn_off:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.hallway_switch_updated_by_webhook
            - service: input_text.set_value
              target:
                entity_id: input_text.hallway_switch_state
              data:
                value: "off"

scene:
  - id: 'scene-blinds-vent'
    name: Blinds vent
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-blinds-living-morning'
    name: Blinds Living Morning
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-blinds-living-morning-hot'
    name: Blinds Living Morning Hot
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-blinds-living-privacy'
    name: Blinds Living Privacy
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-blinds-all-up'
    name: Blinds All Up
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-blinds-all-down'
    name: Blinds All Down
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-blinds-tilt-open'
    name: Blinds Tilt Open
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-blinds-tilt-close'
    name: Blinds Tilt Close
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-blinds-all-down-open'
    name: Blinds All Down Open
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-blinds-down-open'
    name: Blinds Down Open
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-blinds-morning'
    name: Blinds Morning
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-living-down-open'
    name: Blinds Living Down Open
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-living-down-close'
    name: Blinds Living Down Close
    entities: { }
    icon: mdi:blinds
    metadata: { }
  - id: 'scene-living-down-privacy'
    name: Blinds Living Down Privacy
    entities: { }
    icon: mdi:blinds
    metadata: { }
