shelly:
  module: shelly_app
  class: ShellyHallway
  shelly_cor_host: 127.0.0.1
  shelly_cor_token: !secret shelly_cor_token
  shelly_cor_pass: !secret shelly_cor_pass

venting:
  module: vent
  class: Venting
  hum_sensor: sensor.aqarabathroom_humidity
  vent_switch: switch.shellyplus1_083af202ae44_switch_0
