repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
        -   id: mypy
            name: mypy
            entry: /bin/bash -c "PATH=\"venv/bin:$PATH\" MYPYPATH=\"ph4_esp32/\" mypy --ignore-missing-imports $*"
            files: "^ph4_esp32/"
            types: [file, python]
            language: system
-   repo: local
    hooks:
        -   id: pytest
            name: pytest
            entry: ./pytest.sh
            language: python
            pass_filenames: false
            always_run: true
            # alternatively you could `types: [python]` so it only runs when python files change
            # though tests might be invalidated if you were to say change a data file
default_language_version:
    python: python3.9
