name: Pre-commit Check

# This workflow is triggered on push and pull request events
on: [push, pull_request]

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install and Run pre-commit
      run: |
        pip3 install -U pre-commit mypy pytest
        pre-commit run --all-files
